let
  inherit (flake.inputs.nixpkgs) lib;
  flake = builtins.getFlake (toString ./.);

  # Personal key for decrypting/editing secrets locally.
  adminKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHAMADENOb8Pe0kysfLc6BxK2VUiPMt57IOaDYa7J/M5";

  /**
    Find all public keys for nodes that match the given predicate.
  */
  getPublicKeysWhere =
    predicate:
    lib.pipe flake.outputs.colmenaHive.nodes [
      (lib.filterAttrs (_: node: predicate node))
      (lib.mapAttrsToList (_: node: node.config.lab.host.publicKeys))
      (lib.flatten)
    ];

  /**
    Build the full key list for a secret: admin key + matching node keys.
  */
  keysFor = predicate: [ adminKey ] ++ getPublicKeysWhere predicate;
in

{
  # Tailscale OAuth client secret for automatic node authentication.
  # Create at: https://login.tailscale.com/admin/settings/oauth
  # Scope: auth_keys (write), with tags containing all lab node tags.
  "modules/platforms/nixos/lab/services/vpn/tailscale-oauth.age".publicKeys = keysFor (
    node: node.config.lab.services.vpn.client.enable
  );

  # Cloudflare API token for ACME DNS-01 challenge.
  # Create at: https://dash.cloudflare.com/profile/api-tokens
  # Permissions: Zone DNS Edit + Zone Read for selfhosted.city
  "modules/platforms/nixos/lab/services/ingress/cloudflare-api-token.age".publicKeys = keysFor (
    node: node.config.lab.services.ingress.enable
  );

  # Restic REST server htpasswd file for client authentication.
  # Generate entries with: htpasswd -nB workstation-hostname
  "modules/platforms/nixos/lab/services/restic-server/restic-htpasswd.age".publicKeys = keysFor (
    node: node.config.lab.services.restic-server.enable
  );

  # Home Assistant long-lived access token for Prometheus scraping.
  # Create at: HA Profile → Long-Lived Access Tokens
  "modules/platforms/nixos/lab/stacks/observability/ha-prometheus-token.age".publicKeys = keysFor (
    node: node.config.lab.stacks.observability.enable
  );

  # Grafana secret key. Used to encrypt secrets stored in Grafana's database.
  # Generated by: `openssl rand -base64 32`
  "modules/platforms/nixos/lab/stacks/observability/grafana-secret-key.age".publicKeys = keysFor (
    node: node.config.lab.stacks.observability.enable
  );

  # Cloudflare Tunnel token for public ingress.
  "modules/platforms/nixos/lab/services/tunnel/cloudflare-tunnel-token.age".publicKeys = keysFor (
    node: node.config.lab.services.tunnel.enable
  );
}
